### ISSUE TITLE
Mouse move speed is ignored and defaults to 10

### ISSUE THREAD

**Issue by danbulant** [divy-work/autopilot-deno#10]
Hey there.
I was trying to speed up the mouse move, and tried using 0.1, 1 and 20 to test out which is the fastest, but all of them are equal and in console, `d` always appears as 10 (that's a bit of another issue - mouseMove always logs it's params, but it's not as bad as this).

**Comment by tionis** [comment]
@danbulant I took a look at the code and changing the speed of the mouse is not implemented yet. It is just always set to 10.

**Comment by divy-work** [comment]
@danbulant @tionis Yeah, the mouse speed is not yet implemented. You will find it in tommorow's release.

**Comment by divy-work** [comment]
@danbulant I guess the problem is solved in the new release. Don't forget to remove the previous release by delete the `.deno_plugin` folder. (Fixed the mousemove logs too)
