### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by nhrones** [divy-work/autopilot-deno#11]
I'd love to see a simple YouTube demo of Autopiilot.  With this native I/O and ability to capture bitmap, how hard would it be to manipulate the screen bitmap to build a mini 'Electron'?

**Comment by divy-work** [comment]
@nhrones Sure. Why not? I'll have upload screen recordings to the docs as well.

**Comment by divy-work** [comment]
@nhrones Add few demos to the docs.

https://autopilot.divy.work/#-pixelcolor
