### ISSUE TITLE
Segmentation fault when running on Mac

### ISSUE THREAD

**Issue by samuelteixeiras** [divy-work/autopilot-deno#12]
deno run --allow-env --allow-write --allow-read --allow-net --unstable --allow-plugin --reload  autopilot.ts 
Compile file:///Users/samuelteixeira/Documents/deno/autopilot.ts
Download https://raw.githubusercontent.com/divy-work/autopilot-deno/master/mod.ts
Download https://raw.githubusercontent.com/divy-work/autopilot-deno/master/plugin/index.js
Download https://raw.githubusercontent.com/divy-work/autopilot-deno/master/types.ts
Download https://raw.githubusercontent.com/manyuanrong/deno-plugin-prepare/master/mod.ts
Compile https://raw.githubusercontent.com/manyuanrong/deno-plugin-prepare/master/mod.ts
Download https://raw.githubusercontent.com/manyuanrong/deno-plugin-prepare/master/deps.ts
Download https://deno.land/std@v0.51.0/fs/exists.ts
Download https://deno.land/x/checksum@1.4.0/mod.ts
Download https://deno.land/x/checksum@1.4.0/hash.ts
Download https://deno.land/x/checksum@1.4.0/sha1.ts
Download https://deno.land/x/checksum@1.4.0/md5.ts
Download https://deno.land/std@v0.51.0/log/mod.ts
Download https://deno.land/std@v0.51.0/path/mod.ts
Compile https://deno.land/std@v0.51.0/log/mod.ts
Download https://deno.land/std@v0.51.0/log/logger.ts
Download https://deno.land/std@v0.51.0/log/handlers.ts
Download https://deno.land/std@v0.51.0/testing/asserts.ts
Download https://deno.land/std@v0.51.0/log/levels.ts
Download https://deno.land/std@v0.51.0/log/levels.ts
Download https://deno.land/std@v0.51.0/fmt/colors.ts
Download https://deno.land/std@v0.51.0/testing/diff.ts
Compile https://deno.land/std@v0.51.0/path/mod.ts
Download https://deno.land/std@v0.51.0/path/win32.ts
Download https://deno.land/std@v0.51.0/path/posix.ts
Download https://deno.land/std@v0.51.0/path/common.ts
Download https://deno.land/std@v0.51.0/path/separator.ts
Download https://deno.land/std@v0.51.0/path/interface.ts
Download https://deno.land/std@v0.51.0/path/glob.ts
Download https://deno.land/std@v0.51.0/path/_constants.ts
Download https://deno.land/std@v0.51.0/path/_util.ts
Download https://deno.land/std@v0.51.0/path/_globrex.ts
INFO downloading deno plugin "autopilot_deno" from "https://github.com/divy-work/autopilot-deno/releases/latest/download/libautopilot_deno.dylib"
INFO load deno plugin "autopilot_deno" from local "/Users/samuelteixeira/Documents/deno/.deno_plugins/autopilot_deno_5a886ecea39dcd1615a56a8f3ea30d0f.dylib"
Segmentation fault: 11

My mac: Mojave version 10.14.6

**Comment by samuelteixeiras** [comment]
https://gist.github.com/samuelteixeiras/15c4e911d42e64420db4a45cfeec2adf file

**Comment by divy-work** [comment]
@samuelteixeiras Did you use the `--unstable` flag?

**Comment by samuelteixeiras** [comment]
deno run --allow-env --allow-write --allow-read --allow-net **--unstable** --allow-plugin --reload autopilot.ts

**Comment by divy-work** [comment]
Could you try deleting the `.deno_plugins` folder in your working directory and try again? Looks like a problem with previous release.

**Comment by divy-work** [comment]
Also, I think there are too many methods called at the same time. Maybe try calling just `.moveMouse` in the script of the above does not work.

**Comment by divy-work** [comment]
@samuelteixeiras This is was fixed in the new version, it was probably an issue with the new Deno ops.
