### ISSUE TITLE
Windows: getMonitors() return value

### ISSUE THREAD

**Issue by DefinitelyMaybe** [divy-work/autopilot-deno#17]
Firstly, cool work! I had a quick look into the 'Writing Deno Plugins' issue, and it sounds like everything works really nicely together.

**Describe the bug**
Played around with printing some of the return values. getMonitors() returned `1` but I have `2` monitors. small thing. No idea how, or where, or why. Can test later if you wish.

**To Reproduce**
1. `console.log(pilot.getMonitors())`
2. See 1 instead of 2

**Expected behavior**
Expected `2` got `1`.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by divy-work** [comment]
@DefinitelyMaybe This usually happens when Autopilot fails to detect the number of monitors and as a fallback return `1`. 

Could you try running the below code as a batch file? It should output `Monitors: 2`

```bat
for /F %%M in ('
    wmic path Win32_PnPEntity where "Service='monitor' and Status='OK'" get DeviceID /VALUE ^
        ^| find /C "="
') do echo Monitors: %%M
```

**Comment by DefinitelyMaybe** [comment]
```
find: ‘C’: No such file or directory
find: ‘=’: No such file or directory
```
Sorry, I don't know enough about batch files to adjust the script to get it to run correctly.

**Comment by divy-work** [comment]
@DefinitelyMaybe So the script is probably broken and this is why it fails and fallbacks to 1.
I don't have access to Windows but I'll try to look into the issue.

**Comment by divy-work** [comment]
@DefinitelyMaybe Could you try running it outside the batch file (in the cmd itself).

**Comment by DefinitelyMaybe** [comment]
still same thing. added a pause statement, ran from cmd.exe, same error as above.

```batch
for /F %%M in ('
    wmic path Win32_PnPEntity where "Service='monitor' and Status='OK'" get DeviceID /VALUE ^
        ^| find /C "="
') do echo Monitors: %%M
pause
```
```
for /F %M in (' wmic path Win32_PnPEntity where "Service='monitor' and Status='OK'" get DeviceID /VALUE   | find /C "=" ') do echo Monitors: %M
find: '/C': No such file or directory
find: '=': No such file or directory
```

**Comment by divy-work** [comment]
Make sure find.exe is available from cmd by typing `find`.

**Comment by divy-work** [comment]
Also, how are you running the batch file? Autopilot runs it like this `cmd /C monitors.bat`

**Comment by divy-work** [comment]
@DefinitelyMaybe I tried it on Windows 64-bit.

![It works](https://user-images.githubusercontent.com/34997667/84161456-ec033d00-aa8c-11ea-8a30-c24a5a20c610.jpeg)

This is probably a problem with the find command itself. I'm planning to remove it from the batchfile.

This should output the list of monitors available(without the use of find):
```bat
for /F %%M in ('
    wmic path Win32_PnPEntity where "Service='monitor' and Status='OK'" get DeviceID /VALUE
') do echo Monitors: %%M
```

**Comment by DefinitelyMaybe** [comment]
Both are still a no go on my end. Again, sorry not sure why.
I'm running windows 10 Pro.
`find` is available on both powershell and cmd.
Same result when running the bat file from powershell and cmd.
![monitors](https://user-images.githubusercontent.com/5512440/84342755-77e6a780-abfa-11ea-9282-421f542833cf.PNG)
![monitors2](https://user-images.githubusercontent.com/5512440/84342758-7a490180-abfa-11ea-8ffd-84d1fa0849a8.PNG)

**Comment by divy-work** [comment]
@DefinitelyMaybe The below command gets rid of the `find` method:
Try running this instead
```bat
for /F %%M in ('
    wmic path Win32_PnPEntity where "Service='monitor' and Status='OK'" get DeviceID /VALUE
') do echo Monitors: %%M
```

**Comment by divy-work** [comment]
@DefinitelyMaybe The second screen shot prints a lot of echos into the terminal.
These are monitor details. It found 2 monitors.

> Monitors: DeviceID:DISPLAY\DELD011\....
> Monitors: DeviceID:DISPLAY\SAM0B42\....

This proves the the command works without find. I've also found an issue with the batch file not being executed by autopilot. Will fix it in the next release.

**Comment by divy-work** [comment]
@DefinitelyMaybe Looks like it is fixed. Also, `.getMonitors` returns a promise now.

```typescript
console.log(await pilot.getMonitors);
```
(Don't forget to use reload `--reload` to download the latest version.

**Comment by divy-work** [comment]
@DefinitelyMaybe Leaving upto you to close this issue if it's solved.
