### ISSUE TITLE
CACHE env var is ignored

### ISSUE THREAD

**Issue by b-fuze** [divy-work/autopilot-deno#19]
**Describe the bug**
The line here will always produce `checkCache: true` ignoring whether the `CACHE` env var was set or not
https://github.com/divy-work/autopilot-deno/blob/a091c759a0a1857664727a79ba1e27fcfcc3b42f/plugin/index.ts#L27

**To Reproduce**
Use the plugin out of dev mode

**Expected behavior**
Take the `CACHE` env variable into account 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Not sure if that was intentional, but I thought I'd point it out.

**Comment by divy-work** [comment]
Thanks for pointing it out  @b-fuze 
Will fix it today. You can open a PR too if you want.

**Comment by divy-work** [comment]
@b-fuze  Fixed.
