### ISSUE TITLE
Can't start autopilot under windows

### ISSUE THREAD

**Issue by darkship** [divy-work/autopilot-deno#20]
On windows:
I run this
```
import AutoPilot from 'https://raw.githubusercontent.com/divy-work/autopilot-deno/master/mod.ts';

var pilot = new AutoPilot();
```
But I got an error: 
```
PS C:\Users\IEUser\Downloads> deno run --unstable  -A .\autopilot.ts
Compile file:///C:/Users/IEUser/Downloads/autopilot.ts
[2020-06-12T10:47:35.601Z INFO] Downloading latest Autopilot release from Github
INFO loading autopilot plugin "autopilot_deno" from local "C:\Users\IEUser\Downloads\.autopilot_plugin\autopilot_deno_01d30cec9d205cfbaac871ba17c0ba9e.dll"
error: Uncaught Error: The specified module could not be found. (os error 126)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.openPlugin ($deno$/ops/plugins.ts:4:15)
    at prepare (https://raw.githubusercontent.com/divy-work/autopilot-plugin-prepare/master/mod.ts:66:15)
    at async https://raw.githubusercontent.com/divy-work/autopilot-deno/master/plugin/index.ts:26:20
```

My setup:
`PS C:\Users\IEUser\Downloads> deno --version
deno 1.0.5
v8 8.4.300
typescript 3.9.2`

**Comment by divy-work** [comment]
@darkship could you show the contents of `.autopilot_plugin` folder

**Comment by darkship** [comment]
```
PS C:\Users\IEUser\Downloads> ls .\autopilot.ts


    Directory: C:\Users\IEUser\Downloads


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/06/2020     03:47            150 autopilot.ts
```

**Comment by divy-work** [comment]
@darkship Not `autopilot.ts`. I meant `.autopilot_plugin`.

Run `dir .autopilot_plugin` and paste the output

**Comment by darkship** [comment]
sorry, I edited my post

**Comment by divy-work** [comment]
I couldn't reproduction the issue. Could you try again in a new folder?

**Comment by darkship** [comment]
doesn't work...
on Linux I had to re-install deno because `--unstable` didn't exists

**Comment by divy-work** [comment]
@darkship This is a big in the current version of Deno. Tommorow they plan to release a fix for it.
https://discord.com/channels/684898665143206084/684911491035430919/720987126468182157

**Comment by divy-work** [comment]
@darkship Today's release should fix the bug. Could you try upgrading Deno `deno upgrade` and try again?

**Comment by darkship** [comment]
I tried on two different windows, one of them still has this issue

**Comment by divy-work** [comment]
If you're getting the same error message even after upgrading to Deno 1.1.0, this is a deno bug itself.

You can try:
* Create a fresh directory and try again.
Or
* Reinstall deno 1.1.

If none of them work, it is worth an issue at the Deno repo.

**Comment by darkship** [comment]
The windows where it didn't work is a fresh windows install.

The windows where it worked is a development computer so it already had some development component like msbuild or c++ compiler.

=>I installed it on the fresh windows and now it works too.
