### ISSUE TITLE
Documentation: Clarify Keymap

### ISSUE THREAD

**Issue by tionis** [divy-work/autopilot-deno#8]
At the current state of the documentation it is unclear what strings to specify to address specific keys. Does this follow the same standard as xmodmap, how to specify only one key (e.g. w) to toggle.

**Comment by divy-work** [comment]
@tionis The documentation is not mature yet, I'm working on adding the KeyMap as well. I plan to keep this really simple and easy for the users, they should be able to toggle a key with many keycodes, for example: "enter", "return", "next"...etc should be considered as "enter". This makes it easy for users to write programs as they won't have to refer to the docs for getting the exact keycode.

**Comment by divy-work** [comment]
The keymap is added to the docs.
